import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Sparkles } from 'lucide-react';
import { FilterBar } from '@/features/dashboard/components/filter-bar';
import { MemberAvatars } from '@/features/dashboard/components/member-avatars';
import { NewTaskButton } from '@/features/dashboard/components/new-task-button';
import { useI18n } from '@/i18n/use-i18n';
export const BoardHeader = ({ title, subtitle, members, onCreateTask, activeFilter, onFilterChange, selectedPriority, onPriorityChange, groupedByPriority, onToggleGroup, descendingSort, onToggleSort, }) => {
    const { t } = useI18n();
    return (_jsxs("section", { className: "rounded-2xl border border-border/70 bg-card/72 p-3.5 shadow-panel sm:p-4", children: [_jsxs("div", { className: "flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between", children: [_jsxs("div", { className: "min-w-0 space-y-1.5", children: [_jsxs("div", { className: "inline-flex items-center gap-2 rounded-md border border-border/70 bg-background/35 px-2.5 py-1 text-[11px] font-medium text-muted-foreground", children: [_jsx(Sparkles, { size: 13 }), t('board.activeWorkspace')] }), _jsx("h2", { className: "break-words text-lg font-semibold tracking-tight sm:text-xl lg:text-[1.35rem]", children: title }), _jsx("p", { className: "max-w-2xl break-words text-sm text-muted-foreground", children: subtitle }), _jsxs("div", { className: "flex flex-wrap items-center gap-1.5 pt-0.5", children: [_jsx("span", { className: "rounded-full border border-border/70 bg-background/30 px-2 py-0.5 text-[10px] text-muted-foreground", children: t('board.sprintBoard') }), _jsx("span", { className: "rounded-full border border-primary/35 bg-primary/10 px-2 py-0.5 text-[10px] text-foreground", children: t('board.updated') }), _jsx("span", { className: "rounded-full border border-primary/45 bg-primary/15 px-2 py-0.5 text-[10px] text-foreground", children: t('board.selectedBoardBadge') })] })] }), _jsxs("div", { className: "flex w-full flex-col items-start justify-center gap-2.5 self-start sm:w-auto sm:items-end lg:self-center", children: [_jsx(MemberAvatars, { members: members }), _jsx(NewTaskButton, { onClick: onCreateTask })] })] }), _jsx("div", { className: "mt-3.5 border-t border-border/60 pt-3.5", children: _jsx(FilterBar, { activeFilter: activeFilter, onFilterChange: onFilterChange, selectedPriority: selectedPriority, onPriorityChange: onPriorityChange, groupedByPriority: groupedByPriority, onToggleGroup: onToggleGroup, descendingSort: descendingSort, onToggleSort: onToggleSort }) })] }));
};
